version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    platform: linux/x86_64
    image: "mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

volumes:
  db-data: